### ISSUE TITLE
Reporte de practica

### ISSUE THREAD

**Issue by MariaC232** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-MariaC232#2]
[Textbox.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-MariaC232/files/6347322/Textbox.pdf)

**Comment by IMA-G** [comment]
20 %
Buen trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado
